abstract class TodoCubitStates{}
class TodoinitState extends TodoCubitStates{}
class AddedTaskState extends TodoCubitStates{}
class EditTaskState extends TodoCubitStates{}
class EditTodoState extends TodoCubitStates{}
class RemoveTasksState extends TodoCubitStates{}
class GetAllTasksLoadingState extends TodoCubitStates{}
class GetAllTasksSuccessState extends TodoCubitStates{}
class GetAllTasksErrorState extends TodoCubitStates{}
class StoreNewTaskLoadingState extends TodoCubitStates{}
class StoreNewTaskSuccessState extends TodoCubitStates{}
class StoreNewTaskErrorState extends TodoCubitStates{}
class ImageLoadingState extends TodoCubitStates{}
class ImageSuccessState extends TodoCubitStates{}
class ImageErrorState extends TodoCubitStates{}
class ShowSingleTaskLoadingState extends TodoCubitStates{}
class ShowSingleTaskSuccessState extends TodoCubitStates{}
class ShowSingleTaskErrorState extends TodoCubitStates{}
class UpdateTaskLoadingState extends TodoCubitStates{}
class UpdateTaskSuccessState extends TodoCubitStates{}
class UpdateTaskErrorState extends TodoCubitStates{}
class DeleteTaskLoadingState extends TodoCubitStates{}
class DeleteTaskSuccessState extends TodoCubitStates{}
class DeleteTaskErrorState extends TodoCubitStates{}
class GetStatisticsLoadingState extends TodoCubitStates{}
class GetStatisticsSuccessState extends TodoCubitStates{}
class GetStatisticsErrorState extends TodoCubitStates{}
class GetMoreTasksLoadingState extends TodoCubitStates{}
class GetMoreTasksSuccessState extends TodoCubitStates{}
class GetMoreTasksErrorState extends TodoCubitStates{}

